/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(derandomizer.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(fcf25ef5e13973065ecf57a16b2650a2)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/Fengyun2/derandomizer.h>
// pydoc.h is automatically generated in the build directory
#include <derandomizer_pydoc.h>

void bind_derandomizer(py::module& m)
{

    using derandomizer    = gr::Fengyun2::derandomizer;


    py::class_<derandomizer, gr::block, gr::basic_block,
        std::shared_ptr<derandomizer>>(m, "derandomizer", D(derandomizer))

        .def(py::init(&derandomizer::make),
           D(derandomizer,make)
        )
        



        ;




}








