/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(header_skip.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(96347d8b5ad7cf9897d7bdd7765ceaba)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/Fengyun2/header_skip.h>
// pydoc.h is automatically generated in the build directory
#include <header_skip_pydoc.h>

void bind_header_skip(py::module& m)
{

    using header_skip    = gr::Fengyun2::header_skip;


    py::class_<header_skip, gr::block, gr::basic_block,
        std::shared_ptr<header_skip>>(m, "header_skip", D(header_skip))

        .def(py::init(&header_skip::make),
           D(header_skip,make)
        )
        



        ;




}








